### ISSUE TITLE
Deprecation notice: borderless-accounts endpoints

### ISSUE THREAD

**Issue by jayaddison** [jayaddison/pywisetransfer#24]
The `borderless-accounts` API endpoints are deprecated, so an alternative mechanism should be provided to access account details - likely the [Account Details API](https://docs.wise.com/api-docs/api-reference/bank-account-details).

Originated-from emfcamp/Website#1328

**Comment by sasha42** [comment]
It seems that the `borderless-accounts` API has been deactivated this morning - all of my API calls are failing. I'm trying to use the new [Retrieving a balance account statement](https://docs.wise.com/api-docs/api-reference/balance-statement#get) endpoint, however I'm hitting a `403 Client Error: Forbidden` error each time.

I'm not sure if this related to the new SCA protection applied to accounts in UK and EEA. I haven't found a way of getting my API working again so far.

**Comment by marksteward** [comment]
@sasha42 have you looked into your authentication? Our account is still working fine, but it's concerning to think it'll go away without warning.

**Comment by sasha42** [comment]
Just reinstalled my project, and double checked the credentials - I use an API key as well as a public key, which were correct and worked to pull data as recently as the 10th of March. Alas, I still get the same error. Here it is in detail:
```
Traceback (most recent call last):
  File "/Users/sasha/LittleMoney/venv/lib/python3.9/site-packages/pywisetransfer/endpoint.py", line 31, in perform_2fa_if_needed
    return caller(*args, **kwargs)
  File "/Users/sasha/LittleMoney/venv/lib/python3.9/site-packages/apiron/client.py", line 286, in call
    response.raise_for_status()
  File "/Users/sasha/LittleMoney/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.transferwise.com/v3/profiles/XXXXXX/borderless-accounts/XXXXXXX/statement.json?currency=USD&intervalStart=2024-01-14T12%3A51%3A47.900744Z&intervalEnd=2024-03-14T12%3A51%3A47.900744Z
```

@marksteward I suspect this might be to the region that my account is based in (UK and EEA). The [Wise documentation](https://docs.wise.com/api-docs/api-reference/balance-statement#get) mentions that some of the endpoints are SCA protected. 

Additionally, when I open the _Manage your public keys_ page, I see this big message, and my buttons are greyed out:
<img width="766" alt="Capture d’écran 2024-03-14 à 14 00 22" src="https://github.com/jayaddison/pywisetransfer/assets/1775702/5ba819ff-9a09-42bf-bf2c-ce82ba7a9ea4">

**Comment by marksteward** [comment]
Ahh OK, looks like the reauth period is shorter if you have an EU address associated with your account. So ours will probably expire soon too. Thanks for the heads up!

**Comment by marksteward** [comment]
We should also add some logging, because the exception [line](https://github.com/jayaddison/pywisetransfer/blob/d69faf2/pywisetransfer/endpoint.py#L36) suggests X-2FA-Approval-Result is not REJECTED, but we don't know what it actually is.

**Comment by sasha42** [comment]
Thanks for digging into this @marksteward. How would one set up manual auth? I'm not quite sure I understood their documentation on this. My read was that you needed a _client_secret_ that required a partnership with their Wise Platform API, however I might be wrong.

**Comment by jayaddison** [comment]
@sasha42 thanks for the bugreport, and I sympathise with the challenges getting things working - but if it's OK, could you take that question up with Wise support?

We may be able to offer some informal help here, but they should be building their own documentation, local knowledge base, support team etc to handle questions themselves (so redirecting there should, if anything, help them become better aware of what problems customers are running into; while contrastingly this isn't a support forum).
