### ISSUE TITLE
Can't verify webhook signatures

### ISSUE THREAD

**Issue by Naturious** [jayaddison/pywisetransfer#4]
I'm using Chalice, and getting the raw body as a binary payload and trying to pass `verify_signature(raw_body, signature)` with signature being the x-signature-sha256 header. I'm always getting False as a verify_signature result regardless of the webhook call that's made. They're going through correctly through my server and I've tried numerous formats and encoding schemes.
Please help.

**Comment by jayaddison** [comment]
Hi @Naturious - a small disclaimer to begin with that I'm the sole developer of this project, and it isn't sponsored or supported by anyone, so.. keep your support expectations low :)

That said, I'll be glad to help as much as I can.  Some questions that might help us diagnose the problem:

- Is this a test or a production environment? (please be very careful not to include any production credentials or webhooks)
- Has the behaviour of the `verify_signature` call changed recently, or is this the first time you're using it?
- Are you able to add debugging and/or step through the Python code as it runs in your application?

**Comment by Naturious** [comment]
- This is a test environment, checked that the pywisetransfer.environment is sandbox
- It's the first time I'm using it, and I even tried implementing my own logic for validation, but I couldn't validate the signatures either
- Yes, perfectly. But even when I tried stepping through every part and debugging closely, I didn't know what to look for except for checking the data types for the payload/signature, and basic checks like that.

Thank you very much for your response, I highly appreciate it as this part is critical for a project of mine.

**Comment by jayaddison** [comment]
@Naturious no problem.

One idea: could you triple-check that the webhook address you have configured in your Wise sandbox environment matches the endpoint where you receive the webhooks, and that the API key you're using is the one from the sandbox environment?

(the fact that you weren't able to validate the signatures using your own code makes me wonder whether there could be a mismatch between the API key and the webhook signatures)

**Comment by Naturious** [comment]
I'm actually receiving the webhook calls so the endpoint matches the webhook address.
As for the API key I'm not using the API key, isn't that just use to make outgoing calls to Wise servers?

**Comment by jayaddison** [comment]
Thanks for checking - and yep, my mistake.  I forgot that the signature verification uses public keys published by Wise.  As you've probably noticed, they're [baked into the repository](https://github.com/jayaddison/pywisetransfer/blob/2563e368746311f4215d421d47aa182b48b4e03f/pywisetransfer/keys.py), and at the time-of-writing are still up-to-date with the ones published in the [API docs](https://api-docs.transferwise.com/#webhook-events-event-http-requests).

Could you try adding one of the webhook payloads you receive into the [webhook unit tests](https://github.com/jayaddison/pywisetransfer/blob/2563e368746311f4215d421d47aa182b48b4e03f/test/test_webhooks.py) to see whether that helps figure out anything about where the problem is occurring?

**Comment by Naturious** [comment]
Well for one from trying that I figured I had extra spaces on my payload as shown in the picture:
![image](https://user-images.githubusercontent.com/11638808/116792754-94adf700-aaba-11eb-8c29-935fe7038c91.png)
But even after removing those still I can't get the test to go through for my payload (For yours it works just fine).
For now I'll try to play around with these values see why it doesn't go through.

**Comment by Naturious** [comment]
PERFECT, got it to work by getting the x-signature header instead of x-sha-256. Thank you very very much @jayaddison, I don't know how I can ever repay you. If you ever need anything concerning AWS or Serverless, I'd be more than glad to help, you just saved me a lot of headaches.

**Comment by jayaddison** [comment]
Great to hear that @Naturious - and thank you!
