### ISSUE TITLE
Filter argument to profiles.list doesn't work

### ISSUE THREAD

**Issue by russss** [jayaddison/pywisetransfer#5]
This filter statement always returns true because of the `or p.type` part:

https://github.com/jayaddison/pywisetransfer/blob/2563e368746311f4215d421d47aa182b48b4e03f/pywisetransfer/profile.py#L17

(Happy to commit fixes to these if you give me committer access, or we can fork it, but I'm focused on getting stuff working at the moment so I'll just work around this one.)

**Comment by jayaddison** [comment]
Thanks - I'm preparing a pull request for this, and I'll also add you as a committer.
