### ISSUE TITLE
unexpected test failure: test_client_live_environment

### ISSUE THREAD

**Issue by jayaddison** [jayaddison/pywisetransfer#6]
Despite running tests isolated per-process as [instructed in the `README`](https://github.com/jayaddison/pywisetransfer/blame/2563e368746311f4215d421d47aa182b48b4e03f/README.md#L54) (`poetry run pytest --forked`), the `test_client_live_environment` test is failing when I run unit tests locally:

```
================================================================ FAILURES ================================================================
______________________________________________________ test_client_live_environment ______________________________________________________
def test_client_live_environment():
        import pywisetransfer
    
        pywisetransfer.api_key = "live-key"
        pywisetransfer.environment = "live"
        client = pywisetransfer.Client()
    
        domain = client.borderless_accounts.service.domain
>       assert "api.sandbox.transferwise" not in domain
E       AssertionError: assert 'api.sandbox.transferwise' not in 'https://api...ferwise.tech'
E         'api.sandbox.transferwise' is contained here:
E           https://api.sandbox.transferwise.tech

test/test_client_live.py:9: AssertionError
======================================================== short test summary info =========================================================
FAILED test/test_client_live.py::test_client_live_environment
====================================================== 1 failed, 9 passed in 0.55s =======================================================
```

Figure out what's going on there, and resolve the problem.  It's likely an import-resolution-ordering issue related to:

- [`Base.domain` initialization](https://github.com/jayaddison/pywisetransfer/blob/2563e368746311f4215d421d47aa182b48b4e03f/pywisetransfer/base.py#L8-L12)
- [`environment` configuration in `test_client_live_environment`](https://github.com/jayaddison/pywisetransfer/blob/2563e368746311f4215d421d47aa182b48b4e03f/test/test_client_live.py#L5)

As a temporary workaround, individual test files can be run, but that's annoying and unacceptable as a routine development workflow.

**Comment by marksteward** [comment]
I think it might be clearer to move `api_key` and `environment` to the Client object.

**Comment by jayaddison** [comment]
Yep, I agree.  I was trying to be too clever attempting to make those act like write-once variables at module scope.  It's not worth the edge cases it raises.
